SHORTLIST_THRESHOLD: float = 70.0

SCORE_WEIGHTS: dict[str, float] = {
    "skills": 0.20,
    "experience_years": 0.20,
    "work_alignment": 0.30,
    "projects": 0.20,
    "qualification": 0.10,
}

DEGREE_WEIGHTS: dict[str, int] = {
    "Computer Engineering": 10,
    "CSIT": 9,
    "BIT": 8,
    "STEM": 6,
    "Management": 3,
    "Others": 1,
}

DEGREE_CATEGORIES: list[str] = [
    "Computer Engineering",
    "CSIT",
    "BIT",
    "STEM",
    "Management",
    "Others",
]

SUPPORTED_RESUME_FORMATS: list[str] = [".pdf", ".docx"]


PII_ALLOW_LIST: list[str] = list(
    set(
        [
            # Programming Languages
            "Python",
            "JavaScript",
            "TypeScript",
            "Java",
            "C++",
            "C#",
            "Rust",
            "Go",
            "Golang",
            "PHP",
            "Ruby",
            "Swift",
            "Kotlin",
            "Scala",
            "HTML",
            "CSS",
            "SQL",
            "NoSQL",
            "Bash",
            "Shell",
            # Frameworks
            "React",
            "Angular",
            "Vue",
            "Next.js",
            "Django",
            "Flask",
            "FastAPI",
            "Spring Boot",
            "Laravel",
            "Express",
            "Node.js",
            "Tailwind",
            "Bootstrap",
            "Pyramid",
            "Flutter",
            "React Native",
            # Cloud & DevOps
            "AWS",
            "Amazon Web Services",
            "Azure",
            "GCP",
            "Google Cloud",
            "S3",
            "EC2",
            "Lambda",
            "Docker",
            "Kubernetes",
            "K8s",
            "Terraform",
            "Jenkins",
            "Ansible",
            "Git",
            "GitHub",
            "GitLab",
            "CI/CD",
            "CircleCI",
            "Bitbucket",
            "Prometheus",
            "Grafana",
            "ELK",
            "CloudFormation",
            # Data & ML
            "TensorFlow",
            "PyTorch",
            "Keras",
            "Scikit-learn",
            "Pandas",
            "NumPy",
            "Matplotlib",
            "Seaborn",
            "HuggingFace",
            "Transformers",
            "LLM",
            "RAG",
            "NLP",
            "Computer Vision",
            "CNN",
            "RNN",
            "LSTM",
            "BERT",
            "GPT",
            "MLOps",
            "Airflow",
            "MLflow",
            "Spark",
            "Hadoop",
            "Kafka",
            "LangChain",
            "LlamaIndex",
            "Groq",
            # Databases
            "PostgreSQL",
            "MySQL",
            "MongoDB",
            "Redis",
            "ElasticSearch",
            "Neo4j",
            "Cassandra",
            "DynamoDB",
            "Snowflake",
            "BigQuery",
            "MariaDB",
            "SQLite",
            "Oracle",
            # General Tech
            "API",
            "REST",
            "RESTful",
            "GraphQL",
            "Microservices",
            "Serverless",
            "Agile",
            "Scrum",
            "SDLC",
            "JSON",
            "XML",
            "JWT",
            "OAuth",
            "SaaS",
            "PaaS",
            "IaaS",
            "Unit Testing",
            "TDD",
            "BEX",
            "BCT",
            "BEI",
            "CSIT",
            "BIT",
            "BCA",
            "BIM",
        ]
    )
)
