"""remove_redundant_profile_fields

Revision ID: a01b18f4f1e2
Revises: 6f01d4722332
Create Date: 2025-10-21 15:13:04.018575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a01b18f4f1e2'
down_revision: Union[str, Sequence[str], None] = '6f01d4722332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove redundant columns from profile table
    op.drop_column('profile', 'full_name')
    op.drop_column('profile', 'email')
    # Note: Foreign key constraints are not supported in SQLite for existing tables
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back the redundant columns (for rollback)
    op.add_column('profile', sa.Column('email', sa.VARCHAR(), nullable=False))
    op.add_column('profile', sa.Column('full_name', sa.VARCHAR(), nullable=False))
    # Note: Foreign key constraints are not supported in SQLite for existing tables
    # ### end Alembic commands ###
