"""initial db setup with users, job, applications, and company

Revision ID: bbc1b850ff7a
Revises:
Create Date: 2025-10-15 23:15:58.563738

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "bbc1b850ff7a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("job", "requirements", existing_type=sqlite.JSON(), nullable=False)
    op.alter_column("job", "skills", existing_type=sqlite.JSON(), nullable=False)
    op.alter_column("job", "benefits", existing_type=sqlite.JSON(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("job", "benefits", existing_type=sqlite.JSON(), nullable=True)
    op.alter_column("job", "skills", existing_type=sqlite.JSON(), nullable=True)
    op.alter_column("job", "requirements", existing_type=sqlite.JSON(), nullable=True)
    # ### end Alembic commands ###
