"""add shortlist status to job table

Revision ID: 686cf481a72e
Revises: fe0f2b338b5e
Create Date: 2026-02-05 22:38:10.423398

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "686cf481a72e"
down_revision: str | Sequence[str] | None = "fe0f2b338b5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job_posting",
        sa.Column(
            "shortlist_status",
            sa.String(),
            nullable=False,
            server_default="not_started",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job_posting", "shortlist_status")
    # ### end Alembic commands ###
