"""add shortlist status to job table

Revision ID: 902682dbc72c
Revises: 686cf481a72e
Create Date: 2026-02-07 21:11:06.635868

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "902682dbc72c"
down_revision: str | Sequence[str] | None = "686cf481a72e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
