"""initial database

Revision ID: fe0f2b338b5e
Revises: 
Create Date: 2026-02-04 01:02:58.772023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe0f2b338b5e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_description',
    sa.Column('job_description_id', sa.Uuid(), nullable=False),
    sa.Column('job_summary', sa.String(), nullable=False),
    sa.Column('job_responsibilities', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('required_qualifications', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('preferred', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('compensation_and_benefits', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('job_description_id')
    )
    op.create_table('organization',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location_city', sa.String(), nullable=True),
    sa.Column('location_country', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_index(op.f('ix_organization_email'), 'organization', ['email'], unique=True)
    op.create_table('reference_job_description',
    sa.Column('referncejd_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('job_summary', sa.String(), nullable=False),
    sa.Column('job_responsibilities', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('required_qualifications', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('preferred', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('compensation_and_benefits', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('referncejd_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('candidate_profile',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('location_city', sa.String(), nullable=True),
    sa.Column('location_country', sa.String(), nullable=True),
    sa.Column('professional_headline', sa.String(), nullable=True),
    sa.Column('professional_summary', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('job_posting',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('job_description_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('location_city', sa.String(), nullable=True),
    sa.Column('location_country', sa.String(), nullable=True),
    sa.Column('location_type', sa.String(), nullable=False),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_indexed', sa.Boolean(), nullable=False),
    sa.Column('auto_shortlist', sa.Boolean(), nullable=False),
    sa.Column('posted_date', sa.Date(), nullable=False),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_description.job_description_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('user_google',
    sa.Column('user_google_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_google_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('candidate_certification',
    sa.Column('candidate_certification_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('certification_name', sa.String(), nullable=False),
    sa.Column('issuing_body', sa.String(), nullable=False),
    sa.Column('credential_id', sa.String(), nullable=True),
    sa.Column('credential_url', sa.String(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('does_not_expire', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profile.profile_id'], ),
    sa.PrimaryKeyConstraint('candidate_certification_id')
    )
    op.create_table('candidate_education',
    sa.Column('candidate_education_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('college_name', sa.String(), nullable=False),
    sa.Column('degree', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profile.profile_id'], ),
    sa.PrimaryKeyConstraint('candidate_education_id')
    )
    op.create_table('candidate_skills',
    sa.Column('candidate_skill_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profile.profile_id'], ),
    sa.PrimaryKeyConstraint('candidate_skill_id')
    )
    op.create_table('candidate_social_links',
    sa.Column('social_link_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profile.profile_id'], ),
    sa.PrimaryKeyConstraint('social_link_id')
    )
    op.create_table('candidate_work_experience',
    sa.Column('candidate_work_experience_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profile.profile_id'], ),
    sa.PrimaryKeyConstraint('candidate_work_experience_id')
    )
    op.create_table('resume',
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('target_job_title', sa.String(), nullable=True),
    sa.Column('custom_summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profile.profile_id'], ),
    sa.PrimaryKeyConstraint('resume_id')
    )
    op.create_table('job_application',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_profile_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('current_status', sa.String(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('ai_score', sa.Integer(), nullable=True),
    sa.Column('ai_analysis', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profile.profile_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job_posting.job_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization_id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.resume_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_table('resume_certification',
    sa.Column('resume_certification_id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('certification_name', sa.String(), nullable=False),
    sa.Column('issuing_body', sa.String(), nullable=False),
    sa.Column('credential_url', sa.String(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('does_not_expire', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.resume_id'], ),
    sa.PrimaryKeyConstraint('resume_certification_id')
    )
    op.create_table('resume_education',
    sa.Column('resume_education_id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('college_name', sa.String(), nullable=False),
    sa.Column('degree', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.resume_id'], ),
    sa.PrimaryKeyConstraint('resume_education_id')
    )
    op.create_table('resume_skills',
    sa.Column('resume_skill_id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.resume_id'], ),
    sa.PrimaryKeyConstraint('resume_skill_id')
    )
    op.create_table('resume_social_links',
    sa.Column('resume_social_link_id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.resume_id'], ),
    sa.PrimaryKeyConstraint('resume_social_link_id')
    )
    op.create_table('resume_work_experience',
    sa.Column('resume_work_experience_id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.resume_id'], ),
    sa.PrimaryKeyConstraint('resume_work_experience_id')
    )
    op.create_table('job_application_status_history',
    sa.Column('status_history_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['job_application.application_id'], ),
    sa.PrimaryKeyConstraint('status_history_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_application_status_history')
    op.drop_table('resume_work_experience')
    op.drop_table('resume_social_links')
    op.drop_table('resume_skills')
    op.drop_table('resume_education')
    op.drop_table('resume_certification')
    op.drop_table('job_application')
    op.drop_table('resume')
    op.drop_table('candidate_work_experience')
    op.drop_table('candidate_social_links')
    op.drop_table('candidate_skills')
    op.drop_table('candidate_education')
    op.drop_table('candidate_certification')
    op.drop_table('user_google')
    op.drop_table('job_posting')
    op.drop_table('candidate_profile')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('reference_job_description')
    op.drop_index(op.f('ix_organization_email'), table_name='organization')
    op.drop_table('organization')
    op.drop_table('job_description')
    # ### end Alembic commands ###
